services:
  postgres:
    image: postgres:18
    container_name: logisticdb
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - ./infra/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=logisticdb
      - PGDATA=/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d logisticdb" ]
      interval: 5s
      retries: 10